files:
  include:
    - 'scss/*.s+(a|c)ss'
    - 'scss/wmq/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.scss'
rules:
  indentation:
    - 2
    -
      size: 2
  force-element-nesting: 0 # due to this error https://github.com/sasstools/sass-lint/issues/575
  no-url-domains: 0
  no-url-protocols: 0
  nesting-depth:
    - 1
    -
      max-depth: 3
